import { LegalDocument } from "@/types";

export const privacyEn: LegalDocument = {
  slug: "privacy",
  product: "TirzeFlow",
  title: "Privacy Policy",
  summary:
    "TirzeFlow is a personal treatment journal. It holds health data you record yourself — weight, doses, measurements, side effects — which is the most sensitive information an app can hold. This policy states exactly what is collected, why, who it is shared with, and how to erase all of it. There is no advertising, no tracking, and nothing is sold.",
  updatedAt: "2026-09-21",
  sections: [
    {
      id: "controller",
      heading: "1. Who is responsible for your data",
      blocks: [
        {
          type: "paragraph",
          text: "TirzeFlow is developed and maintained by Guilherme Passarinho, an individual based in Brazil, who is the data controller for the personal data processed in the app under Brazil's General Data Protection Law (Law 13,709/2018) and equivalent legislation.",
        },
        {
          type: "paragraph",
          text: "For anything related to privacy, including exercising your rights: guilhermepassarinho@gmail.com.",
        },
      ],
    },
    {
      id: "data",
      heading: "2. What the app collects",
      blocks: [
        {
          type: "paragraph",
          text: "Everything below is provided by you. TirzeFlow collects nothing in the background and does not access your calendar, contacts, location, camera, or your device's Health app.",
        },
        {
          type: "paragraph",
          text: "Account data, needed for you to sign in:",
        },
        {
          type: "list",
          items: [
            "Name and email address.",
            "Password, stored only as an argon2id hash — the password itself is never written down and never travels in plain text on the server.",
            "The date and time you accepted the terms of use and this policy.",
            "If you sign in with Google or Apple: your account identifier at that provider and, for Apple, a refresh token used solely to revoke access when you delete your account.",
          ],
        },
        {
          type: "paragraph",
          text: "Profile data, which feeds the app's calculations:",
        },
        {
          type: "list",
          items: [
            "Biological sex, date of birth, and height.",
            "Activity level, starting weight, goal weight, and treatment start date.",
            "Language, unit system, time zone, and treatment phase.",
          ],
        },
        {
          type: "paragraph",
          text: "Health records, which are the content of the journal:",
        },
        {
          type: "list",
          items: [
            "Injections: date and time, dose in milligrams, injection site, lot number, and notes.",
            "Weigh-ins: date and weight.",
            "Body measurements: waist, hip, chest, arm, thigh, and body fat percentage.",
            "Side effects: date, type, severity, and notes.",
            "Workouts: date, type, duration, perceived exertion, and notes.",
            "Nutrition: meals with calories and macronutrients, and water intake.",
            "Any reminders you set.",
          ],
        },
        {
          type: "paragraph",
          text: "Technical data, generated by the session itself:",
        },
        {
          type: "list",
          items: [
            "IP address and app and operating system identification, stored alongside each active session. They let you end sessions and allow misuse of credentials to be detected.",
            "Server logs, which use only your internal identifier — never your name, your email, or any health data.",
          ],
        },
      ],
    },
    {
      id: "sensitive",
      heading: "3. Sensitive health data and your consent",
      blocks: [
        {
          type: "paragraph",
          text: "Weight, measurements, medication dose, and side effects are sensitive personal data concerning health. They are processed only because you gave specific, prominent consent when creating your account, and exclusively for the purposes set out in this policy.",
        },
        {
          type: "paragraph",
          text: "You may withdraw that consent at any time by deleting your account inside the app, which erases all of these records. Withdrawal does not undo processing already carried out while consent was valid, but it ends any further processing.",
        },
      ],
    },
    {
      id: "purposes",
      heading: "4. What the data is used for",
      blocks: [
        {
          type: "list",
          items: [
            "Showing you your own history: weight progression, logged injections, measurements, side effects, workouts, and nutrition.",
            "Calculating the figures the app displays — body mass index, weekly average, calorie and protein targets, maintenance band, and the next injection site in the rotation.",
            "Authenticating you, keeping your session open, and protecting the account against unauthorised access.",
            "Sending strictly operational email: the sign-up verification code and the password reset code. TirzeFlow sends no newsletter, no promotion, and no marketing of any kind.",
          ],
        },
      ],
    },
    {
      id: "what-we-dont-do",
      heading: "5. What TirzeFlow does not do",
      blocks: [
        {
          type: "paragraph",
          text: "This section matters as much as the previous one, and it is verifiable: the app ships no analytics, advertising, or crash reporting library whatsoever.",
        },
        {
          type: "list",
          items: [
            "It does not sell, rent, or trade your data with anyone.",
            "It shows no advertising and does not use your data to target ads.",
            "It does not track you inside or outside the app, and uses no advertising identifiers.",
            "It uses no analytics, telemetry, or crash reporting tools that capture screen contents.",
            "It shares nothing with health plans, employers, pharmaceutical companies, insurers, or data brokers.",
            "It does not use your health data to train artificial intelligence models.",
          ],
        },
      ],
    },
    {
      id: "sharing",
      heading: "6. Who the data is shared with",
      blocks: [
        {
          type: "paragraph",
          text: "Only the service providers required for the app to work, and each receives the bare minimum:",
        },
        {
          type: "list",
          items: [
            "Amazon Web Services (AWS): hosts the server and the database, in the São Paulo region in Brazil. This is where your records are stored.",
            "Resend: sends the operational email. It receives your email address and the verification code — no health data.",
            "Google and Apple: only if you choose to sign in with one of those accounts. Authentication happens on their side, and they receive nothing from the contents of your journal.",
          ],
        },
        {
          type: "paragraph",
          text: "Beyond that, your data will only be disclosed under a court order or a request from a competent authority, within the limits of the law.",
        },
      ],
    },
    {
      id: "storage",
      heading: "7. Where the data lives and for how long",
      blocks: [
        {
          type: "paragraph",
          text: "Data is held on a server located in Brazil, in São Paulo. The connection between the app and the server is always encrypted.",
        },
        {
          type: "paragraph",
          text: "An encrypted backup is taken daily, kept for thirty days, and then discarded. It exists to restore the service in case of failure.",
        },
        {
          type: "paragraph",
          text: "Your records are kept for as long as your account exists. When you delete the account they are erased from the database immediately; backups that still contain them expire within thirty days.",
        },
      ],
    },
    {
      id: "security",
      heading: "8. How the data is protected",
      blocks: [
        {
          type: "list",
          items: [
            "Passwords stored with argon2id, currently OWASP's recommended algorithm.",
            "All traffic between the app and the server protected by TLS.",
            "Session tokens kept in the operating system's secure storage — Keychain on iOS, Keystore on Android — never in a plain file.",
            "Every database query is scoped to your identifier, so the server cannot return someone else's record even if a record identifier is guessed.",
            "Encrypted backups, with the decryption key held off the server.",
          ],
        },
        {
          type: "paragraph",
          text: "No system is immune to incidents. If a security incident occurs that may pose a material risk to your rights, you and Brazil's data protection authority (ANPD) will be notified as required by law.",
        },
      ],
    },
    {
      id: "rights",
      heading: "9. Your rights",
      blocks: [
        {
          type: "paragraph",
          text: "You have, among others, the rights of confirmation, access, correction, anonymisation, portability, erasure, and information about sharing. Three of them are implemented directly in the app:",
        },
        {
          type: "list",
          items: [
            "Access and portability: you can export all of your data in an open, machine-readable format.",
            "Correction: every journal record can be edited or deleted individually, at any time.",
            "Erasure: deleting your account, done inside the app, erases everything.",
          ],
        },
        {
          type: "paragraph",
          text: "For the remaining rights, write to guilhermepassarinho@gmail.com. You will get an answer within fifteen days.",
        },
      ],
    },
    {
      id: "deletion",
      heading: "10. How to delete your account",
      blocks: [
        {
          type: "paragraph",
          text: "Deletion happens entirely inside the app, with no need to contact anyone: open the Profile tab, scroll to the bottom of the screen, and tap Delete account. The app shows what will be erased and asks for confirmation.",
        },
        {
          type: "paragraph",
          text: "Deletion is permanent and cascades: the account and every associated record — profile, injections, weigh-ins, measurements, side effects, workouts, meals, water intake, reminders, and sessions. There is no soft delete and no grace period; the data cannot be recovered afterwards.",
        },
        {
          type: "paragraph",
          text: "If your account was created with Sign in with Apple, the authorisation granted to Apple is revoked at the same moment.",
        },
      ],
    },
    {
      id: "minors",
      heading: "11. Children and adolescents",
      blocks: [
        {
          type: "paragraph",
          text: "TirzeFlow is not intended for anyone under 18 and does not knowingly collect data from that age group. If we learn that an account was created by a minor, it will be deleted. If you are a parent or guardian and believe this has happened, write to guilhermepassarinho@gmail.com.",
        },
      ],
    },
    {
      id: "medical",
      heading: "12. Important health notice",
      blocks: [
        {
          type: "callout",
          title: "The app does not prescribe",
          text: "TirzeFlow is a journal. It records what your prescriber instructed. It does not suggest a dose, does not indicate when to increase or decrease one, does not replace a consultation, and does not constitute medical advice. Any decision about your treatment belongs to the healthcare professional treating you.",
        },
      ],
    },
    {
      id: "changes",
      heading: "13. Changes to this policy",
      blocks: [
        {
          type: "paragraph",
          text: "This policy may be updated. The date of the latest update is always at the top of this page. Any change that materially affects how your data is handled will be announced inside the app before it takes effect.",
        },
      ],
    },
    {
      id: "contact",
      heading: "14. Contact",
      blocks: [
        {
          type: "paragraph",
          text: "Questions, requests, or complaints about privacy: guilhermepassarinho@gmail.com. You may also complain directly to Brazil's National Data Protection Authority (ANPD).",
        },
      ],
    },
  ],
};
